server:
  port: 8088
spring:
  application:
    name: kafka

# Kafka configuration
kafka:
  bootstrap-servers: localhost:9092
  topic: my-topic
  group-id: kk-consumer-group
  partitions: 1
  replication-factor: 1
  auto-offset-reset: earliest
