server:
  port: 8088
spring:
  application:
    name: kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-kafka-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

app:
  kafka:
    topic-name: sample-topic
