server:
  port: 8088
spring:
  application:
    name: rest
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    embedded:
      version: 4.0.2
    uri: mongodb+srv://kasulwarkiran:<db_password>@rest-service-cluster.9fiuwkf.mongodb.net/
    database: Kk_Mark1

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.mongodb: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

